prometheus:
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - host: alertmanager.ai-hr.student.k8s.aet.cit.tum.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: ai-hr-prod-alertmanager-tls
          hosts:
            - alertmanager.ai-hr.student.k8s.aet.cit.tum.de
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: "https://api.ai-hr.student.k8s.aet.cit.tum.de/api/v1/auth/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://api.ai-hr.student.k8s.aet.cit.tum.de/api/v1/auth/index.html?redirect=$request_uri"
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.ai-hr.student.k8s.aet.cit.tum.de
      tls:
        - secretName: ai-hr-prod-prometheus-tls
          hosts:
            - prometheus.ai-hr.student.k8s.aet.cit.tum.de
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: "https://api.ai-hr.student.k8s.aet.cit.tum.de/api/v1/auth/verify"
        nginx.ingress.kubernetes.io/auth-signin: "https://api.ai-hr.student.k8s.aet.cit.tum.de/api/v1/auth/index.html?redirect=$request_uri"