loki:
  gateway:
    ingress:
      enabled: true
      hosts:
        - host: loki.ai-hr-dev.student.k8s.aet.cit.tum.de
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: ai-hr-dev-loki-tls
          hosts:
            - loki.ai-hr-dev.student.k8s.aet.cit.tum.de
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod