global:
  env:
    stage: dev
    host: api.ai-hr-dev.student.k8s.aet.cit.tum.de
    tlsSecret: ai-hr-dev-tls
    corsAllowed: "http://localhost:3000,http://localhost:5173,http://localhost:4200,https://ai-hr-dev.student.k8s.aet.cit.tum.de,https://api.ai-hr-dev.student.k8s.aet.cit.tum.de,https://loki.ai-hr-dev.student.k8s.aet.cit.tum.de,https://prometheus.ai-hr-dev.student.k8s.aet.cit.tum.de,https://alertmanager.ai-hr-dev.student.k8s.aet.cit.tum.de"
    authCookieDomain: ".ai-hr-dev.student.k8s.aet.cit.tum.de"