global:
  env:
    stage: dev
    host: api.aihr-dev.student.k8s.aet.cit.tum.de
    tlsSecret: aihr-dev-tls
    corsAllowed: "http://localhost:3000,http://localhost:5173,http://localhost:4200,https://aihr.student.k8s.aet.cit.tum.de/api/v1/applications"