global:
  env:
    stage: dev
    host: api.ai-hr-dev.student.k8s.aet.cit.tum.de
    tlsSecret: ai-hr-dev-tls
    corsAllowed: "http://localhost:3000,http://localhost:5173,http://localhost:4200,https://ai-hr-dev.student.k8s.aet.cit.tum.de/api/v1/applications"
  grafana:
    ingress:
      hosts:
        - grafana.api.ai-hr-dev.student.k8s.aet.cit.tum.de
      tls:
        - secretName: ai-hr-dev-grafana-tls
          hosts:
            - grafana.api.ai-hr-dev.student.k8s.aet.cit.tum.de

frontend:
  ingress:
    enabled: true
    host: ai-hr-dev.student.k8s.aet.cit.tum.de
    tlsSecret: ai-hr-dev-frontend-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging