global:
  env:
    stage: prod
    host: api.ai-hr.student.k8s.aet.cit.tum.de
    tlsSecret: ai-hr-prod-tls
    corsAllowed: "https://ai-hr.student.k8s.aet.cit.tum.de/api/v1/applications"

frontend:
  ingress:
    enabled: true
    host: ai-hr.student.k8s.aet.cit.tum.de
    tlsSecret: ai-hr-frontend-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

grafana:
  ingress:
    hosts:
      - grafana.ai-hr.student.k8s.aet.cit.tum.de
    tls:
      - secretName: ai-hr-prod-grafana-tls
        hosts:
          - grafana.ai-hr.student.k8s.aet.cit.tum.de

prometheus:
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - host: alertmanager.ai-hr.student.k8s.aet.cit.tum.de
      tls:
        - secretName: ai-hr-prod-alertmanager-tls
          hosts:
            - alertmanager.ai-hr.student.k8s.aet.cit.tum.de
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
  server:
    extraScrapeConfigs: |
      - job_name: aihr-pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - ai-hr             # 只抓 prod
        relabel_configs:
          # 只抓 prometheus.io/scrape="true" 的 Pod
          - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
            action: keep
            regex: "true"

          # 把 PodIP + 注解端口 拼成新 __address__
          - source_labels: [ __meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port ]
            action: replace
            regex: (.+);(.+)
            replacement: $1:$2          # -> 10.0.3.25:8080
            target_label: __address__

          # 替换 metrics 路径（默认 /metrics → /actuator/prometheus 等）
          - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
            action: replace
            target_label: __metrics_path__
            regex: (.+)

          # （可选）给 job 打上 pod 名 / namespace 等标签，方便查询
          - source_labels: [ __meta_kubernetes_pod_name ]
            action: replace
            target_label: pod
          - source_labels: [ __meta_kubernetes_namespace ]
            action: replace
            target_label: namespace