grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          uid: prometheus
          type: prometheus
          url: http://ai-hr-prod-prometheus-server
          access: proxy
          isDefault: true
        - name: loki
          uid: loki
          type: loki
          url: http://ai-hr-prod-loki-gateway
          access: proxy
          jsonData:
            httpHeaderName1: 'X-Scope-OrgID'
          secureJsonData:
            httpHeaderValue1: 'admin'
  ingress:
    hosts:
      - grafana.ai-hr.student.k8s.aet.cit.tum.de
    tls:
      - secretName: ai-hr-prod-grafana-tls
        hosts:
          - grafana.ai-hr.student.k8s.aet.cit.tum.de