global:
  env:
    stage: dev
    host: api.ai-hr-dev.student.k8s.aet.cit.tum.de
    tlsSecret: ai-hr-dev-tls
    corsAllowed: "http://localhost:3000,http://localhost:5173,http://localhost:4200,https://ai-hr-dev.student.k8s.aet.cit.tum.de/api/v1/applications"

frontend:
  ingress:
    enabled: true
    host: ai-hr-dev.student.k8s.aet.cit.tum.de
    tlsSecret: ai-hr-dev-frontend-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging

grafana:
  ingress:
    hosts:
      - grafana.ai-hr-dev.student.k8s.aet.cit.tum.de
    tls:
      - secretName: ai-hr-dev-grafana-tls
        hosts:
          - grafana.ai-hr-dev.student.k8s.aet.cit.tum.de

prometheus:
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - host: alertmanager.ai-hr-dev.student.k8s.aet.cit.tum.de
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: ai-hr-dev-alertmanager-tls
          hosts:
            - alertmanager.ai-hr-dev.student.k8s.aet.cit.tum.de
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
  server:
    ingress:
      enabled: true
      hosts:
        - prometheus.ai-hr-dev.student.k8s.aet.cit.tum.de
      tls:
        - secretName: ai-hr-dev-prometheus-tls
          hosts:
            - prometheus.ai-hr-dev.student.k8s.aet.cit.tum.de
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod