global:
  # 镜像仓库信息（CI/CD 注入）
  ghcrUser: ""
  ghcrRepo: ""
  imageTag: ""

  # Ingress 通用设置
  ingress:
    enabled: true
    className: nginx
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  # 运行环境专属（由 values-dev / prod 覆盖）
  env:
    stage: ""          # dev / prod
    host: ""           # api.ai-hr*.student.k8s.aet.cit.tum.de
    tlsSecret: ""      # ai-hr-*-tls
    # CORS
    corsAllowed: ""          # 由 dev / prod 覆盖
  jwt:
    privateKey: ""           # helm --set-file 注入
    publicKey: ""            # helm --set-file 注入

  # 数据库凭据
  db:
    username: ""
    password: ""

#kube-prometheus-stack:
#  namespaceOverride: ai-hr-monitoring
#  prometheus:
#    prometheusSpec:
#      serviceMonitorSelectorNilUsesHelmValues: false
#      serviceMonitorSelector:
#        matchLabels:
#          release: ai-hr-monitoring

prometheus:
  rbac:
    create: false
  kube-state-metrics:
    enabled: false
  prometheus-node-exporter:
    enabled: false
  pushgateway:
    enabled: false
  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      route:
        receiver: discord
      receivers:
        - name: discord
          webhook_configs:
            - url: http://alertmanager-discord:9094
              send_resolved: true
    ingress:
      enabled: true

  server:
    replicaCount: 1
    rbac:
      create: false
    serviceAccount:
      create: false
      name: prom-sa                 # Helm 会自动生成 Role+Binding，可直接用
    persistentVolume:
      enabled: true
      size: 2Gi
    alertmanagers:
      - static_configs:
          - targets: [ "ai-hr-dev-alertmanager:9093" ]   # Helm 默认 Service 名
    # Alert rules
    serverFiles:
      alerting_rules.yml: |
        groups:
          - name: basic-alerts
            rules:
              - alert: TargetDown
                expr: up == 0
                for: 1m
                labels: { severity: critical }
                annotations:
                  summary: "Target {{ $labels.instance }} down"
                  description: "Instance {{ $labels.instance }} cannot be reached for more than 1 minute."

    extraScrapeConfigs:
      - job_name: ai-hr-pods
        kubernetes_sd_configs:
          - role: pod
            namespaces: # ← 这里先占位，会被 dev/prod 覆盖
              names: [ ]
        relabel_configs:
          # 只抓 prometheus.io/scrape="true" 的 Pod
          - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
            action: keep
            regex: "true"

          # 把 PodIP + 注解端口 拼成新 __address__
          - source_labels: [ __meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port ]
            action: replace
            regex: (.+);(.+)
            replacement: $1:$2          # -> 10.0.3.25:8080
            target_label: __address__

          # 替换 metrics 路径（默认 /metrics → /actuator/prometheus 等）
          - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
            action: replace
            target_label: __metrics_path__
            regex: (.+)

          # （可选）给 job 打上 pod 名 / namespace 等标签，方便查询
          - source_labels: [ __meta_kubernetes_pod_name ]
            action: replace
            target_label: pod
          - source_labels: [ __meta_kubernetes_namespace ]
            action: replace
            target_label: namespace

grafana:
  rbac:
    namespaced: true

  adminPassword: ""

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    className: nginx
    hosts: []           # 在 values-dev / prod 覆盖
    tls: []
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          uid: prometheus
          type: prometheus
          url: http://ai-hr-dev-prometheus-server   # ← Helm 会自动生成此 Service
          access: proxy
          isDefault: true

  alerting:
    # ContactPoint & NotificationPolicy 都支持 YAML Provision
    contactpoints:
      alertmanager-contact.yaml: |
        apiVersion: 1
        contactPoints:
          - orgId: 1
            name: external-alertmanager         # UI 中的显示名
            receivers:
              - type: alertmanager              # 内置接收器
                uid: ext-am
                settings:
                  url: http://ai-hr-dev-alertmanager:9093
    notificationPolicies:
      default.yaml: |
        apiVersion: 1
        policies:
          - orgId: 1
            receiver: external-alertmanager     # 全局默认全部走这条

    ruleFiles:
      alert-rule.yaml: |
        apiVersion: 1
        groups:
          - name: ai-hr-grafana-rules
            interval: 1m
            rules:
              - uid: grafana-target-down
                title: TargetDown (Grafana side)
                condition: A
                data:
                  - refId: A
                    queryType: promql
                    relativeTimeRange:
                      from: 0
                      to: 0
                    datasourceUid: prometheus
                    model:
                      expr: up == 0
                      interval: ""
                noDataState: NoData
                for: 60s
                annotations:
                  summary: "{{ "{{" }} $values.instance {{ "}}" }} down (via Grafana)"
                labels:
                  severity: critical

discordWebhook:
  url: ""