promtail:
  # 日志采集与推送配置
  config:
    logLevel: info
    logFormat: json
    clients:
      - url: http://ai-hr-prod-loki-gateway/loki/api/v1/push
        tenant_id: "promtail"
    snippets:
      scrapeConfigs: |
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
              namespaces:
                names: [ai-hr]
          relabel_configs:
            # 采集所有 namespace/pod/container 的日志并加标签
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_container_name]
              target_label: container
            - source_labels: [__meta_kubernetes_node_name]
              target_label: node
            # 日志路径
            - action: replace
              source_labels: 
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_name
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              regex: (.+);(.+);(.+);(.+)
              replacement: /var/log/pods/*$3/$4/*.log*
              target_label: __path__