apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-job.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/actuator/prometheus"
  labels:
    {{- include "service-job.selectorLabels" . | nindent 4 }}
    prometheus: "true"

spec:
  selector:
    app: {{ include "service-job.fullname" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http