services:
  pgvector:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: pgvector-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hrapp
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_dev:
