services:
  # PostgreSQL database
  postgresql:
    build:
      context: ./postgresql
      dockerfile: ./Dockerfile

  # Authentication service
  service-auth:
    build:
      context: .
      dockerfile: ./service-auth/Dockerfile

  # Job management service
  service-job:
    build:
      context: .
      dockerfile: ./service-job/Dockerfile

  # Application management service
  service-application:
    build:
      context: .
      dockerfile: ./service-application/Dockerfile

  # GenAI service
  service-genai:
    build:
      context: ./service-genai
      dockerfile: ./Dockerfile

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile