version: "3.8"

services:
  # PostgreSQL database
  postgresql:
    image: postgres:15-alpine
    container_name: ai-hr-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ai_hr_db
      - POSTGRES_USER=ai_hr_user
      - POSTGRES_PASSWORD=ai_hr_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ai-hr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_hr_user -d ai_hr_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Authentication service
  service-auth:
    build:
      context: .
      dockerfile: service-auth/Dockerfile
    container_name: ai-hr-auth
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - ai-hr-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ai_hr_db
      - SPRING_DATASOURCE_USERNAME=ai_hr_user
      - SPRING_DATASOURCE_PASSWORD=ai_hr_password
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/v1/auth/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Job management service
  service-job:
    build:
      context: .
      dockerfile: service-job/Dockerfile
    container_name: ai-hr-job
    ports:
      - "8081:8081"
    depends_on:
      postgresql:
        condition: service_healthy
      service-auth:
        condition: service_healthy
    networks:
      - ai-hr-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ai_hr_db
      - SPRING_DATASOURCE_USERNAME=ai_hr_user
      - SPRING_DATASOURCE_PASSWORD=ai_hr_password
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8081/api/v1/jobs/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Application management service
  service-application:
    build:
      context: .
      dockerfile: service-application/Dockerfile
    container_name: ai-hr-application
    ports:
      - "8082:8082"
    depends_on:
      postgresql:
        condition: service_healthy
      service-auth:
        condition: service_healthy
      service-job:
        condition: service_healthy
    networks:
      - ai-hr-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ai_hr_db
      - SPRING_DATASOURCE_USERNAME=ai_hr_user
      - SPRING_DATASOURCE_PASSWORD=ai_hr_password
    volumes:
      - resume-uploads:/app/uploads/resumes
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8082/api/v1/applications/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Assessment service
  service-assess:
    build:
      context: .
      dockerfile: service-assess/Dockerfile
    container_name: ai-hr-assess
    ports:
      - "8083:8083"
    depends_on:
      postgresql:
        condition: service_healthy
      service-auth:
        condition: service_healthy
      service-application:
        condition: service_healthy
    networks:
      - ai-hr-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/ai_hr_db
      - SPRING_DATASOURCE_USERNAME=ai_hr_user
      - SPRING_DATASOURCE_PASSWORD=ai_hr_password
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8083/api/v1/assessments/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ai-hr-network:
    driver: bridge
    name: ai-hr-network

volumes:
  postgres-data:
    driver: local
    name: ai-hr-postgres-data
  resume-uploads:
    driver: local
    name: ai-hr-resume-uploads
