server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: application-service

  grpc:
    client:
      channels:
        gen-ai:
          address: ${GRPC_GEN_AI_SERVICE_HOST:localhost}:${GRPC_GEN_AI_SERVICE_PORT:8079}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/application_db?stringtype=unspecified
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    public-key: ${JWT_PUBLIC_KEY}

  file:
    upload-dir: ./uploads/resumes
    max-file-size: 10485760 # 10MB
    allowed-extensions: [ ".pdf", ".doc", ".docx" ]
    allowed-content-types: [ "application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" ]


logging:
  level:
    de.tum.devops.application: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# CORS configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:"https://ai-hr.student.k8s.aet.cit.tum.de"}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

service:
  auth:
    base-url: ${AUTH_BASE_URL:http://localhost:8080}
  job:
    base-url: ${JOB_BASE_URL:http://localhost:8081}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus