{
 "title": "GenAI",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "AI requets total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ai_requests_total{instance=\"198.18.199.161:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI request created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ai_requests_created{instance=\"198.18.199.161:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "python_info{instance=\"198.18.199.161:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}