apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  selector:
    app: {{ include "frontend.fullname" . }}
  ports:
    - port: 80
      targetPort: http
      name: http
