# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """--------------------------- AI Service ---------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatReply = channel.unary_stream(
                '/ai.AIService/ChatReply',
                request_serializer=ai__pb2.ChatReplyRequest.SerializeToString,
                response_deserializer=ai__pb2.ChatReplyResponse.FromString,
                _registered_method=True)
        self.NormalQA = channel.unary_stream(
                '/ai.AIService/NormalQA',
                request_serializer=ai__pb2.NormalQARequest.SerializeToString,
                response_deserializer=ai__pb2.ChatReplyResponse.FromString,
                _registered_method=True)
        self.ScoreResume = channel.unary_unary(
                '/ai.AIService/ScoreResume',
                request_serializer=ai__pb2.ScoreResumeRequest.SerializeToString,
                response_deserializer=ai__pb2.ScoreResumeResponse.FromString,
                _registered_method=True)
        self.ScoreInterview = channel.unary_unary(
                '/ai.AIService/ScoreInterview',
                request_serializer=ai__pb2.ScoreInterviewRequest.SerializeToString,
                response_deserializer=ai__pb2.ScoreInterviewResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """--------------------------- AI Service ---------------------------
    """

    def ChatReply(self, request, context):
        """Streamed chat with AI assistant. Server streams incremental ai_message tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NormalQA(self, request, context):
        """Streamed chat with AI, normal QA
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreResume(self, request, context):
        """Scores a resume against job requirements.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreInterview(self, request, context):
        """Scores an interview chat against resume and job requirements.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatReply': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatReply,
                    request_deserializer=ai__pb2.ChatReplyRequest.FromString,
                    response_serializer=ai__pb2.ChatReplyResponse.SerializeToString,
            ),
            'NormalQA': grpc.unary_stream_rpc_method_handler(
                    servicer.NormalQA,
                    request_deserializer=ai__pb2.NormalQARequest.FromString,
                    response_serializer=ai__pb2.ChatReplyResponse.SerializeToString,
            ),
            'ScoreResume': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreResume,
                    request_deserializer=ai__pb2.ScoreResumeRequest.FromString,
                    response_serializer=ai__pb2.ScoreResumeResponse.SerializeToString,
            ),
            'ScoreInterview': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreInterview,
                    request_deserializer=ai__pb2.ScoreInterviewRequest.FromString,
                    response_serializer=ai__pb2.ScoreInterviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """--------------------------- AI Service ---------------------------
    """

    @staticmethod
    def ChatReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AIService/ChatReply',
            ai__pb2.ChatReplyRequest.SerializeToString,
            ai__pb2.ChatReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NormalQA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AIService/NormalQA',
            ai__pb2.NormalQARequest.SerializeToString,
            ai__pb2.ChatReplyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreResume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/ScoreResume',
            ai__pb2.ScoreResumeRequest.SerializeToString,
            ai__pb2.ScoreResumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreInterview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIService/ScoreInterview',
            ai__pb2.ScoreInterviewRequest.SerializeToString,
            ai__pb2.ScoreInterviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
