# templates/alertmanager-discord-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-discord
  labels: { app: alertmanager-discord }
spec:
  replicas: 1
  selector: { matchLabels: { app: alertmanager-discord } }
  template:
    metadata: { labels: { app: alertmanager-discord } }
    spec:
      containers:
        - name: webhook
          image: ghcr.io/gnprice/alertmanager-discord:v1.2.0   # tag 任意
          env:
            - name: DISCORD_WEBHOOK
              value: {{ .Values.discordWebhook.url | quote }}
          ports:
            - name: http
              containerPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
spec:
  ports:
    - port: 9094
      name: http
  selector: { app: alertmanager-discord }