apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aihr.releaseName" . }}-db-creds
  labels:
    app.kubernetes.io/part-of: {{ include "aihr.releaseName" . }}
type: Opaque
data:
  DB_USERNAME: {{ ( .Values.global.db.username | default "postgres" ) | b64enc }}
  DB_PASSWORD: {{ ( .Values.global.db.password | default (randAlphaNum 32) ) | b64enc }}
