apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.serviceAccount.server.name | default "ai-hr-dev-prometheus-server" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io