replicaCount: 1

image:
  # 默认拼接：ghcr.io/<user>/<repo>-service-job:<tag>
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8081

# 环境变量（非敏感）
env:
  springProfile: docker
  corsAllowed: ""
  jwtPublicKey: ""
  authBaseUrl: ""

monitoring:
  enabled: true
  scrapeInterval: 15s