replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

image:
  # 默认拼接：ghcr.io/<user>/<repo>-service-genai:<tag>
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8079

monitoring:
  enabled: true
  scrapeInterval: 15s