---
- hosts: aws
  become: yes

  tasks:
    - name: Ensure apt cache is updated (for Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker and Docker Compose plugin (for Ubuntu)
      apt:
        name:
          - docker.io
          - docker-compose-plugin
        state: present
      when: ansible_os_family == "Debian"

    - name: Add the user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create /srv/app directory
      file:
        path: /srv/app
        state: directory
        mode: '0755'

    - name: Copy .env to server
      copy:
        src: .env
        dest: /srv/app/.env
        mode: '0600'

    - name: Copy docker-compose.prod.yml to server
      copy:
        src: docker-compose.prod.yml
        dest: /srv/app/docker-compose.prod.yml
        mode: '0644'