apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-auth.fullname" . }}
  labels:
    {{- include "service-auth.selectorLabels" . | nindent 4 }}
    prometheus: "true"

spec:
  selector:
    app: {{ include "service-auth.fullname" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http