{{- /* 拼接镜像路径 */}}
{{- $user := .Values.global.ghcrUser -}}
{{- $repo := .Values.global.ghcrRepo -}}
{{- $tag  := default "latest" .Values.global.imageTag -}}
{{- $defaultRepo := printf "ghcr.io/%s/%s-service-genai" $user $repo -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-genai.fullname" . }}
  labels:
    app: {{ include "service-genai.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "service-genai.fullname" . }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
      labels:
        app: {{ include "service-genai.fullname" . }}
    spec:
      containers:
        - name: genai
          image: "{{ default $defaultRepo .Values.image.repository }}:{{ default $tag .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
            - name: grpc
              containerPort: 8079
            - name: metrics
              containerPort: 8000
          env:
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"

            # 数据库连接
            - name: DB_HOST
              value: "{{ include "aihr.releaseName" . }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "aihr.releaseName" . }}-db-creds
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aihr.releaseName" . }}-db-creds
                  key: DB_PASSWORD

            # 其余业务配置
            - name: OLLAMA_BASE_URL
              value: {{ .Values.global.ollama.ollamaBaseUrl | quote }}
            - name: OLLAMA_MODEL
              value: {{ .Values.global.ollama.ollamaModel | quote }}
            - name: OLLAMA_API_KEY
              value: {{ .Values.global.ollama.ollamaApiKey | quote }}

          livenessProbe:
            httpGet:
              path: /
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 120