{{- /* 拼接镜像路径 */}}
{{- $user := .Values.global.ghcrUser -}}
{{- $repo := .Values.global.ghcrRepo -}}
{{- $tag  := default "latest" .Values.global.imageTag -}}
{{- $defaultRepo := printf "ghcr.io/%s/%s-service-genai" $user $repo -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service-genai.fullname" . }}
  labels:
    app: {{ include "service-genai.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "service-genai.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "service-genai.fullname" . }}
    spec:
      containers:
        - name: genai
          image: "{{ default $defaultRepo .Values.image.repository }}:{{ default $tag .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfile | quote }}

            # 数据库连接
            - name: DB_HOST
              value: "{{ include "aihr.releaseName" . }}-postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "aihr.releaseName" . }}-db-creds
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aihr.releaseName" . }}-db-creds
                  key: DB_PASSWORD

            # 其余业务配置
            {{- if .Values.global.jwt.privateKey | default .Values.env.jwtPrivateKey }}
            - name: JWT_PRIVATE_KEY
              value: {{ .Values.env.jwtPrivateKey | default .Values.global.jwt.privateKey | quote }}
            {{- end }}
            {{- if .Values.global.jwt.publicKey | default .Values.env.jwtPublicKey }}
            - name: JWT_PUBLIC_KEY
              value: {{ .Values.env.jwtPublicKey | default .Values.global.jwt.publicKey | quote }}
            {{- end }}
            - name: CORS_ALLOWED_ORIGINS
              value: {{ .Values.env.corsAllowed | default .Values.global.env.corsAllowed | quote }}

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
