apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-genai.fullname" . }}
spec:
  selector:
    app: {{ include "service-genai.fullname" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
