kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector:
        matchLabels:
          release: ai-hr-monitoring

  grafana:
    ingress:
      hosts:
        - grafana.ai-hr-monitoring.student.k8s.aet.cit.tum.de
      tls:
        - secretName: ai-hr-prod-grafana-tls
          hosts:
            - grafana.ai-hr-monitoring.student.k8s.aet.cit.tum.de