replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

image:
  # 默认拼接：ghcr.io/<user>/<repo>-service-application:<tag>
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8082

# 环境变量（非敏感）
env:
  springProfile: docker
  corsAllowed: ""
  jwtPublicKey: ""
  authBaseUrl: ""
  jobBaseUrl: ""
  grpcHost: ""
  grpcPort: "8079"

monitoring:
  enabled: true
  scrapeInterval: 15s