name: Build & Push All Docker Images

on:
  push:
    branches:
      - main
      - week*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate .env with proper tag
        run: |
          echo "GHCR_USER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" > .env
          echo "GHCR_REPO=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> .env
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "GHCR_TAG=${{ github.sha }}" >> .env
          else
            echo "GHCR_TAG=dev-${{ github.sha }}" >> .env
          fi

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build all images via docker compose
        run: docker compose -f docker-compose.prod.yml build

      - name: Push all images via docker compose
        run: docker compose -f docker-compose.prod.yml push

  deploy-aws:
    needs: build-and-push
    uses: ./.github/workflows/deploy-aws.yml
    secrets: inherit